---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: postgres-ha-alerts
  namespace: powerdns
  labels:
    release: prometheus
    role: alert-rules
spec:
  groups:
    - name: postgresql-ha.rules
      interval: 30s
      rules:
        # 🟡 ALERT: PostgreSQL replication lag too high
        - alert: PostgresReplicationLagHigh
          expr: |
            (pg_replication_lag{job="postgres-ha-postgresql"} > 30)
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "PostgreSQL replication lag high (instance {{ $labels.instance }})"
            description: "Replication lag is {{ $value }} seconds — check network or replica performance."

        # 🔴 ALERT: PostgreSQL replica missing or not streaming
        - alert: PostgresReplicaMissing
          expr: |
            count(pg_replication_state{state="streaming"}) < 2
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "PostgreSQL replicas missing"
            description: "One or more replicas are not connected or streaming data from the primary."

        # 🔴 ALERT: PostgreSQL primary not writable
        - alert: PostgresPrimaryNotWritable
          expr: |
            (pg_is_in_recovery{job="postgres-ha-postgresql"} == 1)
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "PostgreSQL primary node in recovery mode"
            description: "Primary appears to be in read-only state. Failover may not have occurred properly."

        # 🟡 ALERT: Connection usage high
        - alert: PostgresConnectionHigh
          expr: |
            (pg_stat_activity_count{job="postgres-ha-postgresql"} / pg_max_connections{job="postgres-ha-postgresql"} * 100) > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "PostgreSQL connections high (instance {{ $labels.instance }})"
            description: "{{ $value }}% of connections in use. Consider increasing max_connections or load-balancing queries."

        # 🔴 ALERT: No replication detected
        - alert: PostgresNoReplication
          expr: absent(pg_replication_lag)
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "PostgreSQL has no replication configured"
            description: "No replication lag metric found. This usually means there are no standby nodes configured or replication has stopped."
